version: 2.1

jobs:
  first_job:
    docker:
      - image: circleci/ubunu:3.9
    steps:
      - checkout
      - run: bash runit.sh && echo $FIRST

# Orchestrate our job run sequence
workflows:
  main_workflow:
    jobs:
      - first_job
