version: 2.1

jobs:
  first_job:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gsutil ls

# Orchestrate our job run sequence
workflows:
  main_workflow:
    jobs:
      - first_job:
          context:
            - gcp
