version: 2.1

jobs:
  first_job:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: bash runit.sh && echo $FIRST && echo "done"

# Orchestrate our job run sequence
workflows:
  main_workflow:
    jobs:
      - first_job
